name: Static check source code

on:
  push:
    branches: ['main', 'develop']
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'requirements/dev.txt'
      - name: Install requirements
        run: 'python -m pip install -r requirements/dev.txt'

      - name: Ruff format
        run: 'ruff format --diff'
      - name: Ruff check
        run: 'ruff check --output-format github'
      - name: Mypy
        run: 'mypy .'
